#!/bin/bash

echo
echo "Start install NodeJS..."
echo

curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
apt install -y nodejs

echo
echo "Start install yarn"
echo

npm install -g yarn

echo
echo "Complete!"
echo