#!/bin/bash

finish_message() {
  echo
  echo "Complete!"
  echo
}

# Install node

echo
echo "Start install NodeJS..."
echo

curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs

echo 
read -p "Install yarn? (y/n): " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    finish_message
    exit 1
fi

echo
echo "Start install yarn"
echo

npm install -g yarn

finish_message